var narodnaArray = [
[ '	ATOMSKO SKLONIŠTE: ' , ' Pakleni vozaci ' ],
[ '  ' , ' Za ljubav treba imat.. ' ],
[ ' AZRA: ' , ' Balkan ' ],
[ '  ' , ' A šta da radim ' ],
[ ' ALISA: ' , ' Hej hej decace ' ],
[ '  ' , ' Kesteni ' ],
[ ' ANIMATORI: ' , ' Andjeli  nas zovu da.. ' ],
[ ' BAJAGA: ' , ' Vesela pesma ' ],
[ '  ' , ' Plavi safir ' ],
[ '  ' , ' 20. vek ' ],
[ '  ' , ' Moji su drugovi ' ],
[ '  ' , ' Jer ti se ljubiš ' ],
[ '  ' , ' Samo nam je ljubav  ' ],
[ ' BABE: ' , ' Noc bez sna ' ],
[ '  ' , ' Ko me tero  ' ],
[ ' BIJELO DUGME: ' , ' Lažeš zlato… ' ],
[ '  ' , ' Svi marš na ples ' ],
[ '  ' , ' Ružica si bila  ' ],
[ '  ' , ' Ne spavaj mala moja ' ],
[ '  ' , ' Na zadnjem sjedištu ' ],
[ '  ' , ' Napile se ulice ' ],
[ '  ' , ' Ako ima boga ' ],
[ '  ' , ' Ajdemo u planine ' ],
[ ' GALIJA: ' , ' Kotor ' ],
[ '  ' , ' Digni ruku ' ],
[ ' GENERACIJA 5: ' , ' Dolazim za 5 minuta ' ],
[ '  ' , ' Ti I ja ' ],
[ ' GIBONI: ' , ' Tempera ' ],
[ '  ' , ' Libar ' ],
[ '  ' , ' Cinim pravu stvar ' ],
[ '  ' , ' Zedjam ' ],
[ ' DEJAN CUKIC: ' , ' Letnje kiše ' ],
[ '  ' , ' Ja bih da pevam ' ]

];
