<?php 
$zabavnaArray = [
[ '	ATOMSKO SKLONIŠTE ' , ' Pakleni vozaci ' ],
[ '' , ' Za ljubav treba imat.. ' ],
[ ' AZRA ' , ' Balkan ' ],
[ '' , ' A šta da radim ' ],
[ ' ALISA ' , ' Hej hej decace ' ],
[ '' , ' Kesteni ' ],
[ ' ANIMATORI ' , ' Andjeli  nas zovu da.. ' ],
[ ' BAJAGA ' , ' Vesela pesma ' ],
[ '' , ' Plavi safir ' ],
[ '' , ' 20. vek ' ],
[ '' , ' Moji su drugovi ' ],
[ '' , ' Jer ti se ljubiš ' ],
[ '' , ' Samo nam je ljubav  ' ],
[ ' BABE ' , ' Noc bez sna ' ],
[ '' , ' Ko me tero  ' ],
[ ' BIJELO DUGME ' , ' Lažeš zlato… ' ],
[ '' , ' Svi marš na ples ' ],
[ '' , ' Ružica si bila  ' ],
[ '' , ' Ne spavaj mala moja ' ],
[ '' , ' Na zadnjem sjedištu ' ],
[ '' , ' Napile se ulice ' ],
[ '' , ' Ako ima boga ' ],
[ '' , ' Ajdemo u planine ' ],
[ ' GALIJA ' , ' Kotor ' ],
[ '' , ' Digni ruku ' ],
[ ' GENERACIJA 5 ' , ' Dolazim za 5 minuta ' ],
[ '' , ' Ti I ja ' ],
[ ' GIBONI ' , ' Tempera ' ],
[ '' , ' Libar ' ],
[ '' , ' Cinim pravu stvar ' ],
[ '' , ' Zedjam ' ],
[ ' DEJAN CUKIC ' , ' Letnje kiše ' ],
[ '' , ' Ja bih da pevam ' ]

];

$stranaArray = [
[ ' LIONEL RICHIE ' , ' Hello ' ] ,
[ ' BILL WITHERS ' , ' Aint no sunshine ' ] ,
[ '' , ' Just the two of us ' ] ,
[ ' SHOLA AMA ' , ' You might need some.      ' ] ,
[ ' BEN E KING ' , ' Stand by me ' ] ,
[ ' CESARIA EVORA ' , ' Besame mucho ' ] ,
[ ' CHRIS REA ' , ' Josephine ' ] ,
[ ' SIMPLY RED ' , ' If you don’t know me  ' ] ,
[ '' , ' Something  got me st. ' ] ,
[ '' , ' Stars ' ] ,
[ ' BRUCE WILLIS ' , ' Save the last dance f. ' ] ,
[ ' SHADE ' , ' Smooth operater ' ] ,
[ ' ANA OHA ' , ' Donna con te ' ] ,
[ ' CHER ' , ' Shoop shoop song ' ] ,
[ ' SHIRLEY&CO. ' , ' Shame shame ' ] ,
[ ' BRIAN ADAMS ' , ' Everything  I do … ' ] ,
[ ' GEORGE MICHAEL ' , ' Faith ' ] ,
[ ' BEE GEES ' , ' Stain alive ' ] ,
[ ' VAN HALEN ' , ' Just a gigolo ' ] ,
[ ' DIRE STRAITS ' , ' Walk of life ' ] ,
[ ' JOE COCKER ' , ' Unchain my heart ' ] ,
[ '' , ' Up where we belong ' ] ,
[ ' PAUL YOUNG ' , ' Love is in the air ' ] ,
[ ' TOM JONES ' , ' Sex bomb ' ] ,
[ '' , ' Green green gras of h. ' ] ,
[ ' DONNA SUMMER ' , ' Hot stuff ' ] ,
[ ' TOM JONES ' , ' I feel good ' ] ,
[ ' TINA TURNER ' , ' Simply the best ' ] ,
[ '' , ' Proud Mary ' ] ,
[ '' , ' Rever deep , mount. ' ] ,
[ '' , ' Whats love got to do ' ] ,
[ '' , '  We dont need another hero ' ] ,
[ ' FRANKIE VALLI ' , ' Cant take my eyes of . ' ] ,
[ ' ELVIS PRESLEY ' , ' Suspicious mind ' ] ,
[ '' , ' Always on my mind ' ] ,
[ '' , ' Viva Las Vegas ' ] ,
[ ' MICHAEL SEMBELLO ' , ' Maniac ' ] ,
[ ' JOAN JET ' , ' I love RNR ' ] ,
[ ' ERIC CLAPTON ' , ' Layla ' ] ,
[ '' , ' Wonderful  tonight ' ] ,
[ ' DUFFY ' , ' Mercy ' ] ,
[ ' BIL M.&JENIFER W. ' , ' Time of my life ' ] ,
[ ' ROD STEWART ' , ' Do ya think im sexy ' ] ,
[ ' THE GREASE ' , ' You are all that I want ' ] ,
[ ' ROBIE WILIAMS ' , ' Feel ' ] ,
[ ' AMIE WINEHOUSE ' , ' Valerie ' ] ,
[ '' , ' Rehab ' ] ,
[ ' EROS RAMAZZOTTI ' , ' Cose della vita ' ] ,
[ '' , ' I belong to you *duet ' ] ,
[ ' BARRY WHITE ' , ' My first, my last , my ' ] ,
[ '' , ' Cant get enough of … ' ] ,
[ ' KENY LOGINS ' , ' Footloose ' ] ,
[ ' FAIRGROUND ATTR. ' , ' Perfect ' ] ,
[ ' THE PIONTER SIST. ' , ' So excited ' ] ,
[ ' VAYA CON DIOS ' , ' Johny ' ] ,
[ ' ADRIANO CELENTANO ' , ' 24000 bacci ' ] ,
[ ' TOTO COTUGNO ' , ' L Italiano vero ' ] ,
[ ' ATHENS ' , ' For Real ' ] ,
[ ' AVICII ' , ' Wake me up ' ] ,
[ ' BOB MARLEY ' , ' Could you be loved ' ] ,
[ ' BRUNO MARS ' , ' Lazy song ' ] ,
[ '' , ' Locked out of heaven ' ] ,
[ ' DAVID LEE ROTH ' , ' Just a gigolo ' ] ,
[ ' JAMIE CULLUM ' , ' Everlasting love ' ] ,
[ ' JUANES ' , ' La Camisa Negra ' ] ,
[ ' KOOL & THE GANG  ' , ' Celebration ' ] ,
[ ' MICHEL TELO ' , ' Ai se eu te pego ' ] ,
[ ' ROCO GRANATA ' , ' Marina Marina ' ] ,
[ ' AL  BANO ' , ' Felicita ' ] ,
[ ' ADEL ' , ' Roling in to deep ' ] ,
[ '' , ' Skyfall ' ] ,
[ ' U2 ' , ' One ' ] ,
[ ' OTTAWAN ' , ' D.I.S.C.O. ' ] ,
[ '' , ' Hands up ' ] ,
[ ' BONEY M. ' , ' Daddy cool ' ] ,
[ '' , ' Rasputin ' ] ,
[ '' , ' My baker ' ] ,
[ '' , ' Sunny ' ] ,
[ '' , ' By the rivers of Bab. ' ] ,
[ ' ABBA ' , ' Mama mia ' ] ,
[ ' ARETHA FRANKLIN ' , ' I say a little prayer  ' ] ,
[ ' DUSTY SPRINGFIELD ' , ' Son of a preacher man ' ] ,
[ '' , ' The look of love ' ] ,
[ ' STEVIE WANDER ' , ' I just call to say I love ' ] ,
[ '' , ' Part time lover ' ] ,
[ ' CHRIS DE BURGH ' , ' Lady in red ' ] ,
[ ' ROY ORBISON ' , ' Pretty woman ' ] ,
[ ' LENNY KRAVITZ ' , ' I belong to you ' ] ,
[ ' AEROSMITH ' , ' Don’t wanna miss a th. ' ] ,
[ ' WET WET WET ' , ' Love is allaround ' ] ,
[ ' MANU CHAO ' , ' Mala vida ' ] ,
[ ' THE MONKEEYS ' , ' Im a believer ' ] ,
[ ' LYNYARD SKYNYARD ' , ' Sweet home Alabama ' ] ,
[ ' QUEEN ' , ' Crazy little thing ' ] ,
[ ' WHITESNAKE ' , ' Here I go again ' ] ,
[ '' , ' Fool  for your loving  ' ] ,
[ '' , ' Is this love ' ] ,
[ ' THE DOORS ' , ' LA. woman ' ] ,
[ ' FAITH NO MORE ' , ' Easy ' ] ,
[ ' GNR ' , ' Sweet child of mine ' ] ,
[ ' BON JOVI ' , ' Its my life ' ] ,
[ ' SANTANA ' , ' Smooth ' ] ,
[ ' RHCP ' , ' Dani California  ' ] ,
[ ' BILLY IDOL ' , ' White wedding ' ] ,
[ ' KISS ' , ' I was made for loving  ' ] ,
[ ' DEEP PURPLE ' , ' Smoke on the watter ' ] ,
[ '' , ' Soldier of fortune ' ] ,
[ ' THE BEATLES ' , ' And I love her ' ] ,
[ ' THE WHITE STRIPES ' , ' Seven nation army  ' ] ,
[ ' FRIENDS ' , ' Ill  be there for you ' ] ,
[ ' MAROON 5 ' , ' Moves like Jagger ' ] ,
[ ' FRANK SINATRA ' , ' Fly me to the Moon ' ] ,
[ ' STING ' , ' Fields of gold ' ] ,
[ '' , ' Every breath you take ' ] ,
[ ' GOTYE ' , ' Somebody that I … ' ] ,
[ ' STARDUST ' , ' Music souds better w. ' ] ,
[ ' TEN SHARP ' , ' You... ' ] ,
[ ' PHAREL WILLIAMS ' , ' Happy ' ] ,
[ ' PHIL COLLINS ' , ' Easy lover ' ] ,
[ ' ROD STEWART ' , ' Have I told you ' ] ,
[ ' SIMPLY RED ' , ' Sunrise ' ] ,
[ ' WHAM! ' , ' Wake me up before you go go ' ] ,
[ ' MELANIE FIONA ' , ' Monday morning ' ] ,
[ ' JESSIE J. ' , ' Price tag ' ] 
    
];

$narodnaArray = [
[ ' HARIS DŽINOVIĆ ' , ' Ostariću neću znati ' ] ,
[ '' , ' Ja ne pijem ' ] ,
[ '' , ' Hladno je ugrij me ' ] ,
[ '' , ' Dajte vina ' ] ,
[ '' , ' Laže Mjesec ' ] ,
[ '' , ' I tebe sam sit kafano ' ] ,
[ '' , ' Emina ' ] ,
[ '' , ' Jesu*l dunje procvale ' ] ,
[ '' , ' Amange romale ' ] ,
[ '' , ' Ako možeš ti ' ] ,
[ '' , ' Sjećaš li se one noći ' ] ,
[ '' , ' Kako mi nedostaješ ' ] ,
[ '' , ' Nek mi bude zadnja casa ' ] ,
[ '' , ' Rano je za tugu ' ] ,
[ '' , ' Poznaćeš me i po mraku ' ] ,
[ '' , ' Traži traži ' ] ,
[ '' , ' Muštuluk ' ] ,
[ '' , '' ] ,
[ ' MIROSLAV  ILIĆ ' , ' Luckasta si ti ' ] ,
[ '' , ' Pozdravi je pozdravi ' ] ,
[ '' , ' Devojka iz grada ' ] ,
[ '' , ' Tebi ' ] ,
[ '' , ' Joj Rado joj Radmila ' ] ,
[ '' , ' Polomiću čaše od kristala ' ] ,
[ '' , ' Vino točim a vino ne pijem ' ] ,
[ '' , ' Šta sam ja u tvom životu ' ] ,
[ '' , ' Šumadija ' ] ,
[ '' , ' Smej se smej ' ] ,
[ '' , ' Ova noć ' ] ,
[ '' , ' Božanstvena ženo ' ] ,
[ '' , ' Amerika ,Amerika ' ] ,
[ '' , ' Rastanka se našeg sećam ' ] ,
[ '' , ' Nije život jedna žena ' ] ,
[ '' , ' Još te nešto čini izuzetnom ' ] ,
[ '' , ' Probudi se srce moje ' ] ,
[ '' , ' Of Jano  Jano ' ] ,
[ '    ' , '' ] ,
[ ' LOUIS ' , ' Dudo ' ] ,
[ '' , ' Slike u oku ' ] ,
[ '' , ' Opa opa ' ] ,
[ '' , ' Sve se osim tuge deli ' ] ,
[ '' , '' ] ,
[ '' , '' ] ,
[ ' TOZOVAC ' , ' Prazna čaša na mom.. ' ] ,
[ '' , ' Vlajna ' ] ,
[ '' , ' Violino ne sviraj ' ] ,
[ '' , ' Kupiću ti Danče ' ] ,
[ '' , ' Oči jedne žene  ' ] ,
[ '' , ' Mirjana  ' ] ,
[ '' , ' Zorice  Zoro moja ' ] ,
[ '' , ' Ti si me čekala ' ] ,
[ '' , ' Ovamo cigani ' ] ,
[ '' , ' Jesen u mom sokaku ' ] ,
[ '' , '' ] ,
[ ' TOMA  Z. ' , ' kiša je padala ' ] ,
[ '' , ' Ostao sam sam ' ] ,
[ '' , ' Sanja ' ] ,
[ '' , ' Ljiljana ' ] ,
[ '' , ' Dotako sam dno života ' ] ,
[ '' , ' Kafana je moja sudbina ' ] ,
[ '' , ' Dal je moguće ' ] ,
[ '' , ' Danka ' ] ,
[ '' , ' Hej Branka Branka ' ] ,
[ '' , ' Jelena ' ] ,
[ '' , ' Plakala je , molila me  ' ] ,
[ '' , ' Svirajte noćas samo za nju ' ] ,
[ '' , ' Tamburaši  tamburaši ' ] ,
[ '' , ' Ispod  palme ' ] ,
[ '   ' , '' ] ,
[ ' DŽEJ ' , ' Ne znaš Ti ' ] ,
[ '' , ' Ni jedne usne se... ' ] ,
[ '' , ' Ugasila si me ' ] ,
[ '' , ' Uspeo sam u životu ' ] ,
[ '' , ' Imati pa nemati ' ] ,
[ '' , ' Radjaj sinove  ' ] ,
[ '' , ' Vetrovi me lome ' ] ,
[ '' , ' Sunce ljubavi ' ] ,
[ '' , ' Upalite za mnom sveće ' ] ,
[ '' , '' ] ,
[ ' HALID BEŠLIĆ ' , ' I zanesen tom ljepotom ' ] ,
[ '' , ' Zlatne strune ' ] ,
[ '' , ' Sudbina me na put šalje ' ] ,
[ '' , ' Miljacka ' ] ,
[ '' , ' Prvi poljubac ' ] ,
[ '' , ' Budi budi uvijek srećna ' ] ,
[ '' , ' Neću neću dijamante ' ] ,
[ '' , '' ] ,
[ ' ŠABAN ŠAULIĆ ' , ' S namerom pođoh …. ' ] ,
[ '' , ' Otvori mi svoja vrata ' ] ,
[ '' , ' Sneg je opet Snežana ' ] ,
[ '' , ' Verujem u ljubav ' ] ,
[ '   ' , '' ] ,
[ ' ŽELJKO SAMARDŽIĆ ' , ' Devet hiljada ' ] ,
[ '' , ' Dajte neku lošu ' ] ,
[ '' , ' Ljubavnik  ' ] ,
[ '' , ' Kafanska pevačica ' ] ,
[ '' , ' Sve je moje tvoje ' ] ,
[ '' , ' Bezobrazno zelene ' ] ,
[ '' , ' Pokazi mi sta znas ' ] ,
[ '' , '' ] ,
[ ' CUNE GOJKOVIĆ ' , ' Ljubav mi srce mori ' ] ,
[ '' , ' Janjičar ' ] ,
[ '' , ' Kafu mi draga ispeci ' ] ,
[ '' , ' Jesen stiže rana ' ] ,
[ '' , '' ] ,
[ ' MARINKO ROKVIĆ ' , ' I kad me svi zaborave ' ] ,
[ '' , ' Skitnice ' ] ,
[ '' , ' Ti za ljubav nisi rođena ' ] ,
[ '' , '  Polomio vetar  grane ' ] ,
[ '' , '' ] ,
[ ' ACA LUKAS ' , ' Pesma od bola ' ] ,
[ '' , ' Mala lisica u noći ' ] ,
[ '' , ' Bele ruže   ' ] ,
[ '' , ' Miris tamjana ' ] ,
[ '' , ' Daleko si ,daleko si ' ] ,
[ '' , '' ] ,
[ ' NOVICA Z. ' , ' Splavovi ' ] ,
[ '' , '' ] ,
[ ' SRĐAN M. ' , ' Tebi moja Mazo ' ] ,
[ '' , '' ] ,
[ ' FERID AVDIĆ ' , ' Kad sam dečak bio ' ] ,
[ '' , '' ] ,
[ ' MEDENI MESEC ' , ' Ivana ' ] ,
[ '' , '' ] ,
[ ' RITAM SRCA ' , ' a hoću sad ' ] ,
[ '' , '' ] ,
[ ' LJUBA ALIČIĆ ' , ' Ti ne ličiš ni na jednu ' ] ,
[ '' , ' Lepa Maro ' ] ,
[ '' , ' Dva dobra druga ' ] ,
[ ' SINAN SAKIĆ ' , ' Sudbina me na put  ' ] ,
[ '' , ' Hej evo me ' ] ,
[ '' , '' ] ,
[ ' HASAN DUDIĆ ' , ' Došlo vreme ' ] ,
[ '' , '' ] ,
[ ' TOMISLAV ČOLOVIĆ ' , ' Mali mrav ' ] ,
[ '' , '' ] ,
[ ' BOBAN Z. ' , ' Ciganima srce daću ' ] ,
[ '' , ' Naviko sam ja na ' ] ,
[ '' , '' ] ,
[ ' ZORAN GAJIĆ ' , ' Nisam te nagledao ' ] ,
[ '' , '' ] ,
[ ' DUŠKO KULIŠ ' , ' Bez tebe je gorko v. ' ] ,
[ '' , ' Suzo moja Suzana ' ] ,
[ '' , ' Ti meni lažeš sve ' ] ,
[ '' , '' ] ,
[ ' ŠAKO POLMENTA ' , '  Ljepša od noći ' ] ,
[ '' , '' ] ,
[ ' ALEN ADEMOVIĆ ' , ' Kruška ' ] ,
[ '' , '' ] ,
[ ' RUMBE ' , ' Đurđevdan ' ] ,
[ '' , ' Čajorije šukarije ' ] ,
[ '' , ' Fato mori dušmanke ' ] ,
[ ' BLEK PANTERS ' , ' Ja baraba a ti vila   ' ] ,
[ '' , '' ] ,
[ ' DIMA ' , ' Nije mene duso ubilo ' ] ,
[ '' , '' ] ,
[ ' ŠABAN B. ' , ' Đelem , đelem ' ] ,
[ '' , '' ] ,
[ ' ŠEKI TURKOVIĆ ' , ' Poslednji boem ' ] ,
[ '' , '' ] ,
[ ' MARKO BULAT ' , ' Prijatelji braćo kumovi  ' ] ,
[ '' , ' Eno dole u kafani ' ] ,
[ '' , '' ] ,
[ ' CECA RAZNATOVIĆ ' , ' Tražio si sve ' ] ,
[ '' , ' Šta je to u tvojim v. ' ] ,
[ '' , ' Beograd ' ] ,
[ '' , ' Kad bi bio ranjen ' ] ,
[ '' , ' Znam ' ] ,
[ '' , ' Zaboravi ' ] ,
[ '' , ' Volim te ' ] ,
[ '' , ' Dragane moj ' ] ,
[ '' , ' Votka  ' ] ,
[ '' , ' Bruka ' ] ,
[ '' , ' Grome moj ' ] ,
[ '' , ' Pile ' ] ,
[ '' , ' Nagovori bela žena ' ] ,
[ '' , ' Ko na grani jabuka ' ] ,
[ '' , ' Doktor ' ] ,
[ '' , '' ] ,
[ '' , '' ] ,
[ ' DRAGANA M. ' , ' Kroz šljivike I livade ' ] ,
[ '' , '' ] ,
[ ' LEPA BRENA ' , ' Miki Mićo ' ] ,
[ '' , ' Mile voli disko ' ] ,
[ '' , ' Jedan dan života/duet ' ] ,
[ '' , ' Golube ' ] ,
[ '' , ' Evo zima će ' ] ,
[ '' , ' Duge noge ' ] ,
[ '' , ' Sanjam ' ] ,
[ '' , ' Hajde da se volimo ' ] ,
[ '' , ' Jugoslovenka ' ] ,
[ '' , ' Šeki Šeki ' ] ,
[ '' , ' Čik pogodi  ' ] ,
[ '' , ' Bato bato  ' ] ,
[ '' , ' Mače moje ' ] ,
[ '' , ' Sitnije cile sitnije ' ] ,
[ '' , ' Robinja ' ] ,
[ '' , ' Uđi slobodno ' ] ,
[ '' , ' Recite mu da ga volim ' ] ,
[ '' , ' Cuvala me mama ' ] ,
[ '' , '' ] ,
[ ' HANKA PALDUM ' , ' Crne kose ' ] ,
[ '' , ' Volela sam volela ' ] ,
[ '' , ' Noćas mi srce pati ' ] ,
[ '' , ' Ja te pjesmom zovem ' ] ,
[ '' , ' Zbog tebe ' ] ,
[ '' , ' Zelene oči ' ] ,
[ '' , ' Ali pamtim još ' ] ,
[ '' , '' ] ,
[ ' ANA BEKUTA ' , ' Brojanica ' ] ,
[ '' , ' Crven konac ' ] ,
[ '' , ' Bekrija ' ] ,
[ '' , ' Veseljak ' ] ,
[ '' , ' Oluja ' ] ,
[ '' , ' Zlatiborske zore ' ] ,
[ '' , ' Kralj ponoći ' ] ,
[ '' , '' ] ,
[ '' , '' ] ,
[ ' NADA OBRIĆ ' , ' Dugo te dugo očekujem ' ] ,
[ '' , '' ] ,
[ ' MERIMA NJ. ' , ' Ivanova korita ' ] ,
[ '' , '' ] ,
[ ' GOCA  STOJIĆEVIĆ ' , ' Pusti me da nađem srcu  ' ] ,
[ '' , ' Zagrli me ti ' ] ,
[ '   ' , '' ] ,
[ ' GOCA LAZAREVIĆ ' , ' Oprosti mi što mislim na ' ] ,
[ '' , '' ] ,
[ ' VESNA ZMIJANAC ' , ' Nevera moja ' ] ,
[ '' , ' Ne kunite crne oči ' ] ,
[ '' , ' Jorgovani /duet ' ] ,
[ '' , '' ] ,
[ ' LEPA LUKIĆ ' , ' Srce je moje violina ' ] ,
[ '' , '' ] ,
[ ' USNIJA REDŽEPOVA ' , ' Kazuj krčmo džerimo ' ] ,
[ '' , ' Niška banja ' ] ,
[ '' , ' Živote moj  ' ] ,
[ '' , ' Šta hoćeš bre ' ] ,
[ '' , '' ] ,
[ ' VASILIJA RADOJČIĆ ' , ' Mito bekrijo ' ] ,
[ '' , '' ] ,
[ ' SNEŽANA SAVIĆ ' , ' Tri poljupca hoću ja ' ] ,
[ '' , '' ] ,
[ ' SNEŽANA ĐURIŠIĆ ' , ' Odakle si sele ' ] ,
[ '' , ' Kuće male krečene ' ] ,
[ '' , ' Rekla Nana da mi daš ' ] ,
[ '' , '' ] ,
[ ' ZLATA PETROVIĆ ' , ' Dođi da mi ruke greješ ' ] ,
[ '' , '' ] ,
[ ' MARINA ŽIVKOVIĆ ' , ' Ajde mori dan ,dva ' ] ,
[ '    ' , '' ] ,
[ ' ZORICA BRUNCLIK ' , ' Avlije avlije ' ] ,
[ '' , ' Da zakopčam jeleče ' ] ,
[ '' , '' ] ,
[ ' ZORICA MARKOVIĆ ' , ' Lijte kiše ' ] ,
[ '' , '' ] ,
[ ' SILVANA ARMENULIĆ ' , ' Ciganine , ti što sviraš ' ] ,
[ '' , '' ] ,
[ ' NADA TOPČAGIĆ ' , ' Jutro je ' ] ,
[ '' , '' ] ,
[ ' STAROGRADSKE ' , ' Moja mala nema mane ' ] ,
[ '' , ' Tri metera somota ' ] ,
[ '' , ' Evo banke cigane moj      ' ] ,
[ '' , ' Maruška ' ] ,
[ '' , ' Kad je deda lumpovao ' ] ,
[ '' , ' Ima jedan kućerak u … ' ] ,
[ '' , ' Čamac na Tisi ' ] ,
[ '' , ' Kraj jezera jedna kuća ' ] ,
[ '' , ' Ej Momci mladi ' ] ,
[ '' , ' Dunave ,Dunave ' ] ,
[ '' , ' Kada padne prvi sneg ' ] ,
[ '' , ' Kad te vidim na sokaku  ' ] ,
[ '' , ' Govori se da me varaš ' ] ,
[ '' , ' U tem Somboru ' ] ,
[ '' , ' Ta tvoja suknja plava ' ] ,
[ '' , ' Fijaker stari ' ] ,
[ '' , ' Crven fesić ' ] ,
[ '' , ' Izađi iz moje čaše ' ] ,
[ '' , ' Stani malo kafanski s. ' ] ,
[ '' , ' Jesen u mom sokaku  ' ] ,
[ '' , ' Peče čiča rakiju ' ] ,
[ '' , ' Beogradski mali pijac ' ] ,
[ '' , ' Berem grožđe biram… ' ] ,
[ '' , ' Maro ,Marice ' ] ,
[ '' , ' Ko te ima taj te nema ' ] ,
[ '' , ' Već odavno spremam ' ] ,
[ '' , '' ] ,
[ ' SVADBA NAMENSKE PESME  ' , '' ] ,
[ '' , ' Aj veseli se … ' ] ,
[ '' , ' Trepetiljka trepetala ' ] ,
[ '' , ' U nedelju svadba mi je ' ] ,
[ '' , ' Sestra mi je poručila ' ] ,
[ '' , ' Danas majko ženiš… ' ] ,
[ '' , ' Svadba svadba ' ] ,
[ '' , ' Pevaj ujko ' ] ,
[ '' , ' Obraše se vinogradi ' ] ,
[ '' , ' Reših da se ženim ' ] ,
[ '' , ' Đuvegije gde ste da ste ' ] ,
[ '' , '' ] ,
[ ' MAKEDONSKE PESME ' , ' Makedonsko devojče ' ] ,
[ '' , ' Jovano Jovanke ' ] ,
[ '' , ' Lihnida ' ] ,
[ '' , ' Laži Vere ' ] ,
[ '' , ' Bitola ' ] ,
[ '' , ' Eleno kerko ' ] ,
[ '' , ' Blagunjo dejče mori ' ] ,
[ '' , ' Kako što e taja čaša ' ] ,
[ '' , ' Ako umram il zaginam ' ] ,
[ '' , ' Opa nina nina naj ' ] ,
[ '' , ' Belo lice ljubam jas ' ] ,
[ '' , '' ] ,
[ ' PESME IZ BOSNE ' , ' Višegrade grade ' ] ,
[ '' , ' Krčma u planini ' ] ,
[ '' , ' Prođoh Bosnom ' ] ,
[ '' , ' Snijeg pade na behar… ' ] ,
[ '' , ' Čudna jada od Mostara ' ] ,
[ '' , ' Grana od bora ' ] ,
[ '' , ' Moj dilbere ' ] ,
[ '' , ' Banja Luko I ta tvoja  ' ] ,
[ '' , ' Ne klepeći nanulama ' ] ,
[ '' , ' Zvijezda tjera mjeseca ' ] ,
[ '' , ' Kad ja pođoh na Bem. ' ] ,
[ '' , ' Da zna zora ' ] ,
[ '' , '' ] ,
[ ' PESME IZ KRAJINE ' , ' Krajišnici gde ćemo … ' ] ,
[ '' , ' Koja gora Ivo ' ] ,
[ '' , ' Nema raja ' ] ,
[ '' , ' Oj oraje oraje ' ] ,
[ '' , ' Vila Bana sa planine  ' ] ,
[ '' , '' ] ,
[ ' PESME IZ CRNE GORE ' , ' Pljevaljsi tamburaši  ' ] ,
[ '' , ' Mostovi na Morači ' ] ,
[ '' , ' Pivljanka ' ] ,
[ '' , ' Leti leti bijeli golube ' ] ,
[ '' , ' Što se mala uobrazi  ' ] ,
[ '' , ' Ivana se kroz Berane  ' ] ,
[ '' , ' Oj đevojko Milijana ' ] ,
[ '' , '' ] ,
[ ' PESME SA KOSOVA ' , '  Udade se jagodo ' ] ,
[ '' , ' Vidovdan ' ] ,
[ '' , ' Ječam žela kosovka …. ' ] ,
[ '' , '' ] ,
[ ' PESME IZ SRBIJE ' , ' Ajde Jano ' ] ,
[ '' , ' Zapevala Sojka ptica ' ] ,
[ '' , ' Moj golube ' ] ,
[ '' , ' Mila majko šalji me  ' ] ,
[ '' , ' Na uskrs sam se  ' ] ,
[ '' , ' Lepe li su nano gr.dev ' ] ,
[ '' , '' ] ,
[ ' RUSKE PESME ' , ' Kaćuša    ' ] ,
[ '' , ' Oči čornie ' ] ,
[ '' , ' Ciganoćka ' ] ,
[ '' , ' Kalinka ' ] ,
[ '' , ' Cigani ljubjat pesni ' ] ,
[ '' , ' Podmoskovnie vecera ' ] 

];


function halfarray($array){
    $leng=count($array);
    if($leng % 2 ==0){
        $num = $leng/2;   
    } else {
        $num = ($leng+1)/2;   
    }

    

    if($num < $leng && $array[$num][0] != '' ) {
        $num=$num;
    } elseif ($num < $leng) {
        while($array[$num][0] =='') {
            $num ++;
        }

    }
    return $num;
}


?>